# Generated by Django 4.2 on 2023-05-01 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0004_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='WatchList',
            new_name='watchlist',
        ),
    ]
